version: '2'

services:
  registry:
    image: registry:2.6.0
    restart: always
    container_name: registry
    ports:
      - "5000:5000"
    volumes:
      - ~/.docker-registry-volumes:/var/lib/registry
  web:
    image: konradkleine/docker-registry-frontend:v2
    restart: always
    links:
      - registry
    depends_on:
      - registry
    ports:
      - "8888:80"
    environment:
      ENV_DOCKER_REGISTRY_HOST: registry
      ENV_DOCKER_REGISTRY_PORT: 5000

