version: '2'

services:
  app:
    restart: always
    image: "arukmn/node-image"
    tty: true
    links:
      - redis
      - mysql
      - mongo
    depends_on:
      - redis
      - mysql
      - mongo
    volumes:
      - .:/usr/app
    command: /bin/bash
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: redis-server --appendonly yes
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "my_database"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo-data:/data/db
