version: '2'

services:
  datastore:
    restart: "no"
    build: ./datastore
    volumes:
      - ~/.docker-store/redis-data:/data
      - ~/.docker-store/mongo-data:/data/db
      - ~/.docker-store/mysql-data:/var/lib/mysql
  app:
    restart: always
    build: ./app
    tty: true
    container_name: app
    links:
      - redis
      - "mysql:db"
      - mongo
    depends_on:
      - redis
      - mysql
      - mongo
    # app dir is parent
    volumes:
      - ../:/usr/app
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes_from:
      - datastore
    command: redis-server --appendonly yes
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "my_database"
    ports:
      - "3306:3306"
    volumes_from:
      - datastore
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes_from:
      - datastore
